# IMPORTANT:
# to run with this config:
# VM Options: -Djava.util.logging.config.file=src/main/resources/logging.properties

# logging in console (ConsoleHandler) and in file (FileHandler)
handlers= java.util.logging.ConsoleHandler, java.util.logging.FileHandler
# console level
java.util.logging.ConsoleHandler.level = INFO
# file level
java.util.logging.FileHandler.level = FINE
# file pattern
java.util.logging.FileHandler.pattern = output.%u.log

